'use strict';

// file automatically generated by angular-template-cache

angular
	.module('templates', [])
	.run(['$templateCache', function($templateCache) {
		$templateCache.put('test-it/first.html', '<style>p{background:red}</style><p class="custom class">Custom file</p>');

		$templateCache.put('test-it/second.html', '<script>alert("hello world")</script><div><b>hello</b></div>');
	}
]);
