'use strict';

module.exports = {
	filesGlob: null,
	fileList: [],
	strict: true,
	style: 'browser',
	header: '// file automatically generated by angular-template-cache',
	moduleName: 'templates',
	newModule: true,
	basePath: '',
	quotmark: 'single',
	whitespace: 'tabs',
	htmlmin: true,
	htmlminOptions: {}
};
