'use strict';

module.exports = {
	files: '**html',
	strict: true,
	style: 'browser',
	header: '// file automatically generated by angular-template-cache',
	moduleName: 'templates',
	newModule: true,
	basePath: '',
	quotmark: 'single',
	whitespace: 'tabs'
};
